name: Docker and Ansible CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (using GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push myapp:latest

      # Step 6: Run Ansible playbook to deploy
      #- name: Run Ansible Playbook
       # uses: dawidd6/action-ansible-playbook@v4
        # with:
         # playbook: deploy.yml
